### ISSUE TITLE
Still necessary/usefull for Zope 4?

### ISSUE THREAD

**Issue by htgoebel** [plone/plone.reload#13]
If so, please update Trove classifiers and mention it in the Readme. Thansk.

BTW. There seem to be new Trove Classiifers

Filter Framework :: Zope::2
Filter Framework :: Zope::3
Filter Framework :: Zope::4

**Comment by thet** [comment]
We already have the Zope 4 classifier since quite some time:
https://github.com/plone/plone.reload/commit/a2d4a9edab5c18c22d5113fb080fa063bc4cd93d
